name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Run Linter (Code Style Check)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install black isort flake8

      # pyproject.toml과 .flake8 설정 파일이 존재하는지 확인
      - name: Debug pyproject.toml
        run: cat pyproject.toml || echo "pyproject.toml not found"

      - name: Debug .flake8
        run: cat .flake8 || echo ".flake8 not found"

      # black 실행
      - name: Run black (Code Formatting Check)
        run: black --check .

      # isort 실행
      - name: Run isort (Import Sorting Check)
        run: isort . --check-only

      # flake8 실행
      - name: Run flake8 (Python Lint)
        run: flake8 --config .flake8

  test:
    name: Run Django Tests (SQLite)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Django test database
        env:
          DJANGO_SETTINGS_MODULE: config.settings
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings
        run: |
          python manage.py test accounts
